version: 0.2

phases:
  build:
    commands:
      - ls -la
      - ./gradlew assembleDebug
      - ls -la
      - ls -la app/build/outputs/apk/debug
artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk